version: "3"

services:
  web:
    image: nginx:${NGINX_VERSION:-latest}
    ports:
      - '${NGINX_HTTP_PORT:-8080}:80'
      - '${NGINX_HTTPS_PORT:-443}:443'
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    restart: always
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: 'mysql:${MYSQL_VERSION}'
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/mysql_data:/var/lib/mysql
      - ./docker/db/mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
    restart: always
    depends_on:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PMA_PORT:-4040}:80'
    volumes:
      - ./docker/pma/sessions:/sessions
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - PMA_USER=${PMA_USER}
